### ISSUE TITLE
Debian stable support

### ISSUE THREAD

**Issue by jtkristoff** [lamehost/aggregate-prefixes#2]
It is slightly annoying that this package is not supported in Python 3.7, because that is the current version still shipping with Debian stable (buster).  I believe the primary reason it fails is due the use of the "walrus" operator that was introduced in 3.8 and used by aggregate-prefixes.  Can I convince you to make sure this package supports Debian stable in the future?

**Comment by lamehost** [comment]
@jtkristoff,

Being a long time Debian user, i would do everything to help the project!

I believe [commit 39c5ec602c37562530bfc74c517c492c9ecd17ee](https://github.com/lamehost/aggregate-prefixes/commit/39c5ec602c37562530bfc74c517c492c9ecd17ee) does what you've asked for.
Mind to test it?

**Comment by alistairmackenzie** [comment]
@lamehost 

I can confirm that this works with Python 3.7 on Debian stable :)

**Comment by jtkristoff** [comment]
That seems to work fine for me as well.  I will note, coincidentally Debian bullseye (11) was just released not long ago and of course, it includes an updated version of Python that now supports the walrus operator.  :-)  It might be awhile before everyone has this, but if you really like your old version with it, I wouldn't complain too loudly if you wanted to go back to it.

**Comment by lamehost** [comment]
Thanks both for the update, i am going to keep the code as is anyway. It works, it widen support and i don't see any particular performance decrease.
