### ISSUE TITLE
pypi release v0.6.5 broken

### ISSUE THREAD

**Issue by elandorr** [lamehost/aggregate-prefixes#3]
Due to wrong metadata:
`inconsistent version: expected '0.6.5', but metadata has '0.1.0'`
The new `pyproject.toml` seems to be to blame.

PS: Thank you for publishing this project, it is the **only** one that actually works! All the established ones are dramatically wrong one way or another, and nobody ever seemed to notice or care.

**Comment by lamehost** [comment]
First of all, thanks for reporting it and for the compliments. I don't deserve them.

The `pyproject.toml` file wasn't meant to be there. I'm trying to switch from setuptools to poetry and the file has slipped in unnoticed.

I have removed it in [v0.6.6](https://github.com/lamehost/aggregate-prefixes/releases/tag/v0.6.6).

**Comment by elandorr** [comment]
It really has to be said. Your tool deals with individual IPs (broken in `aggregate`, it sets the mask to the default for all) and masks that run over (nothing else handles this). It's very helpful. And IPv6 too. Even the nftables people had a bug in their merge, and that's still in Deb stable. This is some high quality stuff, 'lamehost'. :)
Have a nice one
